angular.module("angular.prime",[]).run(["$rootScope","puiGrowl",function(d,c){d.safeApply=function(a){var b=this.$root.$$phase;"$apply"==b||"$digest"==b?a&&"function"===typeof a&&a():this.$apply(a)};d.showInfoMessage=function(a,b){c.showInfoMessage(a,b)};d.showWarnMessage=function(a,b){c.showWarnMessage(a,b)};d.showErrorMessage=function(a,b){c.showErrorMessage(a,b)}}]);var PUI={zindex:1E3,scrollInView:function(d,c){var a=parseFloat(d.css("borderTopWidth"))||0,b=parseFloat(d.css("paddingTop"))||0,a=c.offset().top-d.offset().top-a-b,b=d.scrollTop(),i=d.height(),h=c.outerHeight(!0);0>a?d.scrollTop(b+a):a+h>i&&d.scrollTop(b+a-i+h)},isIE:function(d){return $.browser.msie&&parseInt($.browser.version,10)==d},escapeRegExp:function(d){return d.replace(/([.?*+^$[\]\\(){}|-])/g,"\\$1")},escapeHTML:function(d){return d.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,
"&gt;")}};$(function(){var d={primaryStyles:"fontFamily fontSize fontWeight fontVariant fontStyle paddingLeft paddingTop paddingBottom paddingRight marginLeft marginTop marginBottom marginRight borderLeftColor borderTopColor borderBottomColor borderRightColor borderLeftStyle borderTopStyle borderBottomStyle borderRightStyle borderLeftWidth borderTopWidth borderBottomWidth borderRightWidth line-height outline".split(" "),specificStyle:{"word-wrap":"break-word","overflow-x":"hidden","overflow-y":"auto"},simulator:$('<div id="textarea_simulator"/>').css({position:"absolute",
top:0,left:0,visibility:"hidden"}).appendTo(document.body),toHtml:function(c){return c.replace(/\n/g,"<br>").split(" ").join('<span style="white-space:prev-wrap">&nbsp;</span>')},getCaretPosition:function(){var c=d,a=this,b=a[0],i=a.offset();if($.browser.msie){b.focus();var h=document.selection.createRange();$("#hskeywords").val(b.scrollTop);return{left:h.boundingLeft-i.left,top:parseInt(h.boundingTop)-i.top+b.scrollTop+document.documentElement.scrollTop+parseInt(a.getComputedStyle("fontSize"))}}c.simulator.empty();
$.each(c.primaryStyles,function(b,d){a.cloneStyle(c.simulator,d)});c.simulator.css($.extend({width:a.width(),height:a.height()},c.specificStyle));var h=a.val(),j=a.getCursorPosition(),i=h.substring(0,j),h=h.substring(j),j=$('<span class="before"/>').html(c.toHtml(i)),i=$('<span class="focus"/>'),h=$('<span class="after"/>').html(c.toHtml(h));c.simulator.append(j).append(i).append(h);h=i.offset();j=c.simulator.offset();return{top:h.top-j.top-b.scrollTop+($.browser.mozilla?0:parseInt(a.getComputedStyle("fontSize"))),
left:i[0].offsetLeft-c.simulator[0].offsetLeft-b.scrollLeft}}};$.fn.extend({getComputedStyle:function(c){if(0!=this.length){var a=this[0],b=this.css(c);return b=b||($.browser.msie?a.currentStyle[c]:document.defaultView.getComputedStyle(a,null)[c])}},cloneStyle:function(c,a){var b=this.getComputedStyle(a);b&&$(c).css(a,b)},cloneAllStyle:function(c){var a=this[0],b;for(b in a.style){var d=a.style[b];"string"==typeof d||"number"==typeof d?this.cloneStyle(c,b):NaN}},getCursorPosition:function(){var c=
this[0],a=0;if("selectionStart"in c)a=c.selectionStart;else if("selection"in document){var b=document.selection.createRange();if(6<parseInt($.browser.version))c.focus(),a=document.selection.createRange().text.length,b.moveStart("character",-c.value.length),a=b.text.length-a;else{var d=document.body.createTextRange();for(d.moveToElementText(c);0>d.compareEndPoints("StartToStart",b);a++)d.moveStart("character",1);for(b=0;b<=a;b++)"\n"==c.value.charAt(b)&&a++;c=c.value.split("\n").length-1;a-=c}}return a},
getCaretPosition:d.getCaretPosition})});/*
 Rangy Text Inputs, a cross-browser textarea and text input library plug-in for jQuery.

 Part of Rangy, a cross-browser JavaScript range and selection library
 http://code.google.com/p/rangy/

 Depends on jQuery 1.0 or later.

 Copyright 2010, Tim Down
 Licensed under the MIT license.
 Version: 0.1.205
 Build date: 5 November 2010
*/
(function(d){function c(a,b){var g=typeof a[b];return"function"===g||!!("object"==g&&a[b])||"unknown"==g}function a(a,b,g){0>b&&(b+=a.value.length);typeof g==i&&(g=b);0>g&&(g+=a.value.length);return{start:b,end:g}}function b(){return"object"==typeof document.body&&document.body?document.body:document.getElementsByTagName("body")[0]}var i="undefined",h,j,o,m,p,q,r,s,n;d(document).ready(function(){function k(g,e){return function(){var f=this.jquery?this[0]:this,a=f.nodeName.toLowerCase();if(1==f.nodeType&&
("textarea"==a||"input"==a&&"text"==f.type))if(f=[f].concat(Array.prototype.slice.call(arguments)),f=g.apply(this,f),!e)return f;if(e)return this}}var l=document.createElement("textarea");b().appendChild(l);if(typeof l.selectionStart!=i&&typeof l.selectionEnd!=i)h=function(g){var e=g.selectionStart,f=g.selectionEnd;return{start:e,end:f,length:f-e,text:g.value.slice(e,f)}},j=function(g,e,f){e=a(g,e,f);g.selectionStart=e.start;g.selectionEnd=e.end},n=function(g,e){e?g.selectionEnd=g.selectionStart:
g.selectionStart=g.selectionEnd};else if(c(l,"createTextRange")&&"object"==typeof document.selection&&document.selection&&c(document.selection,"createRange"))h=function(g){var e=0,f=0,a,b,c;if((c=document.selection.createRange())&&c.parentElement()==g)b=g.value.length,a=g.value.replace(/\r\n/g,"\n"),f=g.createTextRange(),f.moveToBookmark(c.getBookmark()),c=g.createTextRange(),c.collapse(!1),-1<f.compareEndPoints("StartToEnd",c)?e=f=b:(e=-f.moveStart("character",-b),e+=a.slice(0,e).split("\n").length-
1,-1<f.compareEndPoints("EndToEnd",c)?f=b:(f=-f.moveEnd("character",-b),f+=a.slice(0,f).split("\n").length-1));return{start:e,end:f,length:f-e,text:g.value.slice(e,f)}},j=function(g,e,f){var e=a(g,e,f),f=g.createTextRange(),b=e.start-(g.value.slice(0,e.start).split("\r\n").length-1);f.collapse(!0);e.start==e.end?f.move("character",b):(f.moveEnd("character",e.end-(g.value.slice(0,e.end).split("\r\n").length-1)),f.moveStart("character",b));f.select()},n=function(g,e){var a=document.selection.createRange();
a.collapse(e);a.select()};else{b().removeChild(l);window.console&&window.console.log&&window.console.log("TextInputs module for Rangy not supported in your browser. Reason: No means of finding text input caret position");return}b().removeChild(l);m=function(a,e,b,c){var d;e!=b&&(d=a.value,a.value=d.slice(0,e)+d.slice(b));c&&j(a,e,e)};o=function(a){var e=h(a);m(a,e.start,e.end,!0)};s=function(a){var e=h(a),b;e.start!=e.end&&(b=a.value,a.value=b.slice(0,e.start)+b.slice(e.end));j(a,e.start,e.start);
return e.text};p=function(a,b,f,c){var d=a.value;a.value=d.slice(0,f)+b+d.slice(f);c&&(b=f+b.length,j(a,b,b))};q=function(a,b){var c=h(a),d=a.value;a.value=d.slice(0,c.start)+b+d.slice(c.end);c=c.start+b.length;j(a,c,c)};r=function(a,b,c){var d=h(a),i=a.value;a.value=i.slice(0,d.start)+b+d.text+c+i.slice(d.end);b=d.start+b.length;j(a,b,b+d.length)};d.fn.extend({getSelection:k(h,!1),setSelection:k(j,!0),collapseSelection:k(n,!0),deleteSelectedText:k(o,!0),deleteText:k(m,!0),extractSelectedText:k(s,
!1),insertText:k(p,!0),replaceSelectedText:k(q,!0),surroundSelectedText:k(r,!0)})})})(jQuery);