angular.module("angular.prime").directive("puiGalleria",function(){return{restrict:"A",compile:function(){return function(a,c,b){var d=a.$eval(b.puiGalleria)||{};$(function(){c.puigalleria({panelWidth:d.panelWidth,panelHeight:d.panelHeight})})}}}});$(function(){$.widget("primeui.puigalleria",{options:{panelWidth:600,panelHeight:400,frameWidth:60,frameHeight:40,activeIndex:0,showFilmstrip:!0,autoPlay:!0,transitionInterval:4E3,effect:"fade",effectSpeed:250,effectOptions:{},showCaption:!0,customContent:!1},_create:function(){this.element.addClass("pui-galleria ui-widget ui-widget-content ui-corner-all");this.panelWrapper=this.element.children("ul");this.panelWrapper.addClass("pui-galleria-panel-wrapper");this.panels=this.panelWrapper.children("li");
this.panels.addClass("pui-galleria-panel ui-helper-hidden");this.element.width(this.options.panelWidth);this.panelWrapper.width(this.options.panelWidth).height(this.options.panelHeight);this.panels.width(this.options.panelWidth).height(this.options.panelHeight);this.options.showFilmstrip&&(this._renderStrip(),this._bindEvents());this.options.customContent&&(this.panels.children("img").remove(),this.panels.children("div").addClass("pui-galleria-panel-content"));var a=this.panels.eq(this.options.activeIndex);
a.removeClass("ui-helper-hidden");this.options.showCaption&&this._showCaption(a);this.element.css("visibility","visible");this.options.autoPlay&&this.startSlideshow()},_renderStrip:function(){var a='style="width:'+this.options.frameWidth+"px;height:"+this.options.frameHeight+'px;"';this.stripWrapper=$('<div class="pui-galleria-filmstrip-wrapper"></div>').width(this.element.width()-50).height(this.options.frameHeight).appendTo(this.element);this.strip=$('<ul class="pui-galleria-filmstrip"></div>').appendTo(this.stripWrapper);
for(var c=0;c<this.panels.length;c++){var b=this.panels.eq(c).children("img"),b='<li class="'+(c==this.options.activeIndex?"pui-galleria-frame pui-galleria-frame-active":"pui-galleria-frame")+'" '+a+'><div class="pui-galleria-frame-content" '+a+'><img src="'+b.attr("src")+'" class="pui-galleria-frame-image" '+a+"/></div></li>";this.strip.append(b)}this.frames=this.strip.children("li.pui-galleria-frame");this.element.append('<div class="pui-galleria-nav-prev ui-icon ui-icon-circle-triangle-w" style="bottom:'+
this.options.frameHeight/2+'px"></div><div class="pui-galleria-nav-next ui-icon ui-icon-circle-triangle-e" style="bottom:'+this.options.frameHeight/2+'px"></div>');this.options.showCaption&&(this.caption=$('<div class="pui-galleria-caption"></div>').css({bottom:this.stripWrapper.outerHeight(!0),width:this.panelWrapper.width()}).appendTo(this.element))},_bindEvents:function(){var a=this;this.element.children("div.pui-galleria-nav-prev").on("click.puigalleria",function(){a.slideshowActive&&a.stopSlideshow();
a.isAnimating()||a.prev()});this.element.children("div.pui-galleria-nav-next").on("click.puigalleria",function(){a.slideshowActive&&a.stopSlideshow();a.isAnimating()||a.next()});this.strip.children("li.pui-galleria-frame").on("click.puigalleria",function(){a.slideshowActive&&a.stopSlideshow();a.select($(this).index(),!1)})},startSlideshow:function(){var a=this;this.interval=setInterval(function(){a.next()},this.options.transitionInterval);this.slideshowActive=!0},stopSlideshow:function(){clearInterval(this.interval);
this.slideshowActive=!1},isSlideshowActive:function(){return this.slideshowActive},select:function(a,c){if(a!==this.options.activeIndex){this.options.showCaption&&this._hideCaption();var b=this.panels.eq(this.options.activeIndex),d=this.frames.eq(this.options.activeIndex),f=this.panels.eq(a),e=this.frames.eq(a);b.hide(this.options.effect,this.options.effectOptions,this.options.effectSpeed);f.show(this.options.effect,this.options.effectOptions,this.options.effectSpeed);d.removeClass("pui-galleria-frame-active").css("opacity",
"");e.animate({opacity:1},this.options.effectSpeed,null,function(){$(this).addClass("pui-galleria-frame-active")});this.options.showCaption&&this._showCaption(f);if(void 0===c||!0===c)b=e.position().left,e=this.options.frameWidth+parseInt(e.css("margin-right")),d=this.strip.position().left,b+=d,b+this.options.frameWidth>this.stripWrapper.width()?this.strip.animate({left:"-="+e},this.options.effectSpeed,"easeInOutCirc"):0>b&&this.strip.animate({left:"+="+e},this.options.effectSpeed,"easeInOutCirc");
this.options.activeIndex=a}},_hideCaption:function(){this.caption.slideUp(this.options.effectSpeed)},_showCaption:function(a){a=a.children("img");this.caption.html("<h4>"+a.attr("title")+"</h4><p>"+a.attr("alt")+"</p>").slideDown(this.options.effectSpeed)},prev:function(){0!=this.options.activeIndex&&this.select(this.options.activeIndex-1)},next:function(){this.options.activeIndex!==this.panels.length-1?this.select(this.options.activeIndex+1):(this.select(0,!1),this.strip.animate({left:0},this.options.effectSpeed,
"easeInOutCirc"))},isAnimating:function(){return this.strip.is(":animated")}})});