angular.module("angular.prime",[]).run(function(a){a.safeApply=function(c){var b=this.$root.$$phase;"$apply"==b||"$digest"==b?c&&"function"===typeof c&&c():this.$apply(c)};a.initializeGrowl=function(){void 0==a.growl&&$(function(){a.growl=$("#growl");if(1===a.growl.length)a.growl.puigrowl();else throw"Growl needs a exactly 1 div with id 'growl'";})};a.showInfoMessage=function(c,b){a.initializeGrowl();a.growl.puigrowl("show",[{severity:"info",summary:c,detail:b}])};a.showWarnMessage=function(c,b){a.initializeGrowl();
a.growl.puigrowl("show",[{severity:"warn",summary:c,detail:b}])};a.showErrorMessage=function(c,b){a.initializeGrowl();a.growl.puigrowl("show",[{severity:"error",summary:c,detail:b}])}});var PUI={zindex:1E3,scrollInView:function(a,c){var b=parseFloat(a.css("borderTopWidth"))||0,g=parseFloat(a.css("paddingTop"))||0,b=c.offset().top-a.offset().top-b-g,g=a.scrollTop(),d=a.height(),e=c.outerHeight(!0);0>b?a.scrollTop(g+b):b+e>d&&a.scrollTop(g+b-d+e)},isIE:function(a){return $.browser.msie&&parseInt($.browser.version,10)==a},escapeRegExp:function(a){return a.replace(/([.?*+^$[\]\\(){}|-])/g,"\\$1")},escapeHTML:function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,
"&gt;")}};$(function(){var a={primaryStyles:"fontFamily fontSize fontWeight fontVariant fontStyle paddingLeft paddingTop paddingBottom paddingRight marginLeft marginTop marginBottom marginRight borderLeftColor borderTopColor borderBottomColor borderRightColor borderLeftStyle borderTopStyle borderBottomStyle borderRightStyle borderLeftWidth borderTopWidth borderBottomWidth borderRightWidth line-height outline".split(" "),specificStyle:{"word-wrap":"break-word","overflow-x":"hidden","overflow-y":"auto"},simulator:$('<div id="textarea_simulator"/>').css({position:"absolute",
top:0,left:0,visibility:"hidden"}).appendTo(document.body),toHtml:function(c){return c.replace(/\n/g,"<br>").split(" ").join('<span style="white-space:prev-wrap">&nbsp;</span>')},getCaretPosition:function(){var c=a,b=this,g=b[0],d=b.offset();if($.browser.msie){g.focus();var e=document.selection.createRange();$("#hskeywords").val(g.scrollTop);return{left:e.boundingLeft-d.left,top:parseInt(e.boundingTop)-d.top+g.scrollTop+document.documentElement.scrollTop+parseInt(b.getComputedStyle("fontSize"))}}c.simulator.empty();
$.each(c.primaryStyles,function(a,g){b.cloneStyle(c.simulator,g)});c.simulator.css($.extend({width:b.width(),height:b.height()},c.specificStyle));var e=b.val(),i=b.getCursorPosition(),d=e.substring(0,i),e=e.substring(i),i=$('<span class="before"/>').html(c.toHtml(d)),d=$('<span class="focus"/>'),e=$('<span class="after"/>').html(c.toHtml(e));c.simulator.append(i).append(d).append(e);e=d.offset();i=c.simulator.offset();return{top:e.top-i.top-g.scrollTop+($.browser.mozilla?0:parseInt(b.getComputedStyle("fontSize"))),
left:d[0].offsetLeft-c.simulator[0].offsetLeft-g.scrollLeft}}};$.fn.extend({getComputedStyle:function(c){if(0!=this.length){var b=this[0],a=this.css(c);return a=a||($.browser.msie?b.currentStyle[c]:document.defaultView.getComputedStyle(b,null)[c])}},cloneStyle:function(c,b){var a=this.getComputedStyle(b);a&&$(c).css(b,a)},cloneAllStyle:function(c){var b=this[0],a;for(a in b.style){var d=b.style[a];"string"==typeof d||"number"==typeof d?this.cloneStyle(c,a):NaN}},getCursorPosition:function(){var c=
this[0],b=0;if("selectionStart"in c)b=c.selectionStart;else if("selection"in document){var a=document.selection.createRange();if(6<parseInt($.browser.version))c.focus(),b=document.selection.createRange().text.length,a.moveStart("character",-c.value.length),b=a.text.length-b;else{var d=document.body.createTextRange();for(d.moveToElementText(c);0>d.compareEndPoints("StartToStart",a);b++)d.moveStart("character",1);for(a=0;a<=b;a++)"\n"==c.value.charAt(a)&&b++;c=c.value.split("\n").length-1;b-=c}}return b},
getCaretPosition:a.getCaretPosition})});/*
 Rangy Text Inputs, a cross-browser textarea and text input library plug-in for jQuery.

 Part of Rangy, a cross-browser JavaScript range and selection library
 http://code.google.com/p/rangy/

 Depends on jQuery 1.0 or later.

 Copyright 2010, Tim Down
 Licensed under the MIT license.
 Version: 0.1.205
 Build date: 5 November 2010
*/
(function(a){function c(a,b){var h=typeof a[b];return"function"===h||!!("object"==h&&a[b])||"unknown"==h}function b(a,b,h){0>b&&(b+=a.value.length);typeof h==d&&(h=b);0>h&&(h+=a.value.length);return{start:b,end:h}}function g(){return"object"==typeof document.body&&document.body?document.body:document.getElementsByTagName("body")[0]}var d="undefined",e,i,o,m,p,q,r,s,n;a(document).ready(function(){function k(h,f){return function(){var j=this.jquery?this[0]:this,a=j.nodeName.toLowerCase();if(1==j.nodeType&&
("textarea"==a||"input"==a&&"text"==j.type))if(j=[j].concat(Array.prototype.slice.call(arguments)),j=h.apply(this,j),!f)return j;if(f)return this}}var l=document.createElement("textarea");g().appendChild(l);if(typeof l.selectionStart!=d&&typeof l.selectionEnd!=d)e=function(h){var f=h.selectionStart,a=h.selectionEnd;return{start:f,end:a,length:a-f,text:h.value.slice(f,a)}},i=function(a,f,j){f=b(a,f,j);a.selectionStart=f.start;a.selectionEnd=f.end},n=function(a,f){f?a.selectionEnd=a.selectionStart:
a.selectionStart=a.selectionEnd};else if(c(l,"createTextRange")&&"object"==typeof document.selection&&document.selection&&c(document.selection,"createRange"))e=function(a){var f=0,b=0,c,d,e;if((e=document.selection.createRange())&&e.parentElement()==a)d=a.value.length,c=a.value.replace(/\r\n/g,"\n"),b=a.createTextRange(),b.moveToBookmark(e.getBookmark()),e=a.createTextRange(),e.collapse(!1),-1<b.compareEndPoints("StartToEnd",e)?f=b=d:(f=-b.moveStart("character",-d),f+=c.slice(0,f).split("\n").length-
1,-1<b.compareEndPoints("EndToEnd",e)?b=d:(b=-b.moveEnd("character",-d),b+=c.slice(0,b).split("\n").length-1));return{start:f,end:b,length:b-f,text:a.value.slice(f,b)}},i=function(a,f,c){var f=b(a,f,c),c=a.createTextRange(),e=f.start-(a.value.slice(0,f.start).split("\r\n").length-1);c.collapse(!0);f.start==f.end?c.move("character",e):(c.moveEnd("character",f.end-(a.value.slice(0,f.end).split("\r\n").length-1)),c.moveStart("character",e));c.select()},n=function(a,b){var c=document.selection.createRange();
c.collapse(b);c.select()};else{g().removeChild(l);window.console&&window.console.log&&window.console.log("TextInputs module for Rangy not supported in your browser. Reason: No means of finding text input caret position");return}g().removeChild(l);m=function(a,b,c,e){var d;b!=c&&(d=a.value,a.value=d.slice(0,b)+d.slice(c));e&&i(a,b,b)};o=function(a){var b=e(a);m(a,b.start,b.end,!0)};s=function(a){var b=e(a),c;b.start!=b.end&&(c=a.value,a.value=c.slice(0,b.start)+c.slice(b.end));i(a,b.start,b.start);
return b.text};p=function(a,b,c,e){var d=a.value;a.value=d.slice(0,c)+b+d.slice(c);e&&(b=c+b.length,i(a,b,b))};q=function(a,b){var c=e(a),d=a.value;a.value=d.slice(0,c.start)+b+d.slice(c.end);c=c.start+b.length;i(a,c,c)};r=function(a,b,c){var d=e(a),g=a.value;a.value=g.slice(0,d.start)+b+d.text+c+g.slice(d.end);b=d.start+b.length;i(a,b,b+d.length)};a.fn.extend({getSelection:k(e,!1),setSelection:k(i,!0),collapseSelection:k(n,!0),deleteSelectedText:k(o,!0),deleteText:k(m,!0),extractSelectedText:k(s,
!1),insertText:k(p,!0),replaceSelectedText:k(q,!0),surroundSelectedText:k(r,!0)})})})(jQuery);